add missing positional argument : eqn
Fix Traceback reported by Shaan Subbaiah <shaansubbaiah.cs18@bmsce.ac.in>
Traceback is reported while clicking on 'pi' and 'e' of Toolbar:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/sugar/activities/Calculate.activity/layout.py", line 133, in <lambda>
    lambda w: self._parent.process()],
  File "/usr/share/sugar/activities/Calculate.activity/calculate.py", line 518, in process
    res = self.parser.evaluate(tree)
  File "/usr/share/sugar/activities/Calculate.activity/astparser.py", line 680, in evaluat
e
    raise ParseError(msg, 0)
TypeError: __init__() missing 1 required positional argument: 'eqn'