add 2 missing positional arguments: 'start' and 'eqn'
Submitting / pressing ‘=’ without entering any value throws

1593527598.469328 DEBUG root: Parsing preprocessed equation: ''
Traceback (most recent call last):
  File "/usr/share/sugar/activities/Calculate.activity/layout.py", line 133, in <lambda>
    lambda w: self._parent.process()],
  File "/usr/share/sugar/activities/Calculate.activity/calculate.py", line 517, in process
    tree = self.parser.parse(s)
  File "/usr/share/sugar/activities/Calculate.activity/astparser.py", line 656, in parse
    raise ParseError(msg)
TypeError: __init__() missing 2 required positional arguments: 'start' and 'eqn'

Reported by Shaan Subbaiah <shaansubbaiah.cs18@bmsce.ac.in>
Tested by Saumya Mishra <2017230@iiitdmj.ac.in>