Fix issues occured while raising RuntimeError
eqn was added to RuntimeError, but not passed to the parent
class ParserError
Errors occured while ParserError tried subscripting on the missing eqn
variable
Fix adds the missing arguments while raising RuntimeError

Fixes regressions introduced in eb9d99a

Reproduce:
Type random text (eg. sweetener) -> Hit Enter / Equals symbol (=)

Traceback:
```
1592573782.228379 DEBUG Calculate: Result: RuntimeError("Variable 'sweetener' not defined", 0, 5)
Traceback (most recent call last):
  File "/usr/share/sugar/activities/Calculate.activity/layout.py", line 133, in <lambda>
    lambda w: self._parent.process()],
  File "/usr/share/sugar/activities/Calculate.activity/calculate.py", line 552, in process
    self.set_error_equation(eqn)
  File "/usr/share/sugar/activities/Calculate.activity/calculate.py", line 444, in set_error_equation
    self.set_last_equation(eqn)
  File "/usr/share/sugar/activities/Calculate.activity/calculate.py", line 439, in set_last_equation
    self.layout.last_eq.set_buffer(eqn.create_lasteq_textbuf())
  File "/usr/share/sugar/activities/Calculate.activity/calculate.py", line 219, in create_lasteq_textbuf
    resstr = str(self.result)
  File "/usr/share/sugar/activities/Calculate.activity/astparser.py", line 110, in __str__
    {'a': self.eqn[self._range[0] - 1: self._range[1] - 1],
TypeError: 'NoneType' object is not subscriptable
```

Fixes #67